name: Test and Build

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Setup Docker Buildx
      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v2

      # Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      # Run Lint Tests
      - name: Run linting tests
        run: flake8 --ignore=E501,F401 .

      # Login to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set Docker Image Version
      - name: Generate Version Tag
        run: |
          VERSION=v$(date +"%Y%m%d%H%M%S")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build . -t dineshops/demo-app:${{ env.VERSION }}

      # Push Docker Image
      - name: Push Docker Image
        run: docker push dineshops/demo-app:${{ env.VERSION }}
      
      #Update the k8s manifest files
      - name: Update k8s manifests
        run: |
          cat deploy/deploy.yaml
          sed -i "s|image: dineshops/demo-app:.*|image: dineshops/demo-app:${{ env.VERSION }}|" deploy/deploy.yaml
          cat deploy/deploy.yaml
      #Update Github
      - name: Commit the changes
        run: | 
          git config --global user.email "<>"
          git config --global user.name "Github Actions Bot"
          git add deploy/deploy.yaml
          git commit -m "Update deploy.yaml with new image version -${{ env.VERSION }}"
          git push origin main
